### ISSUE TITLE
I need postcss-nested syntax hightlight

### ISSUE THREAD

**Issue by taro-shono** [hedefalk/atom-vue#6]
Could do you change this??

![screen shot 2015-11-09 at 23 21 04](https://cloud.githubusercontent.com/assets/4067007/11035901/92f1124a-8738-11e5-9459-6b7989697d1a.png)

**Comment by aidistan** [comment]
It's the standard CSS syntax used in `<style></style>` which do not support nested selectors. If you still want that, try to use SCSS instead:

``` scss
<style lang="scss">
body {
  h1 {
    margin: 10px;
  }
}
</style>
```
