### ISSUE TITLE
cssnext nested selector syntax highlighting

### ISSUE THREAD

**Issue by foundryspatial-duncan** [hedefalk/atom-vue#60]
Is there a way to augment the syntax highlighting used between `<style>` tags if we want to use `postcss-cssnext`? I noticed the `language-vue` grammar doesn't highlight nested selectors:
``` css
main { /* 'main' is red */
    & button.foo { /* button and foo are dark grey, the dot is light grey, should be all be red */
        color: pink;
        & span.bar baz { /* span. is light grey, bar and baz are dark grey */
            background: blue;
        }
    }
}
```
